"""Write the JSON Schemas for the curriculum store (editorial/curriculum/schemas/).

Usage: python editorial/tools/curriculum/build_schemas.py
The schemas use the subset of JSON Schema that cur.validate() implements (jsonschema is not installed).
"""
import sys

from cur import save, store

sys.stdout.reconfigure(encoding="utf-8")
DRAFT = "https://json-schema.org/draft/2020-12/schema"
CEFR = {"enum": ["Pre-A1", "A1", "A2", "B1", "B2", "C1", "C2"]}
CFN = {"type": "string", "pattern": r"^CFN-\d{4}$"}
STAT = {"enum": ["GENERATED", "AI_QA", "EDITORIAL_REVIEW", "SPECIALIST_REVIEW", "NATIVE_REVIEW", "APPROVED", "COMPILED", "PUBLISHED", "RETIRED"]}
RES = {"enum": ["PENDING", "PASS", "FAIL", "NOT_REQUIRED", "NOT_PERFORMED"]}


def S(**k):
    return {"type": "string", "minLength": 1, **k}


def arr(items, mn=0):
    a = {"type": "array", "items": items}
    if mn:
        a["minItems"] = mn
    return a


def obj(req, props, extra=False):
    return {"type": "object", "required": req, "properties": props, "additionalProperties": extra}


def doc(title, body):
    return {"$schema": DRAFT, "title": title, **body}


TASK = obj(["id", "type", "prompt", "items", "answers"], {
    "id": S(), "type": {"enum": ["recognition", "gap-fill", "matching", "ordering", "rewriting", "short-answer", "choose-response"]},
    "prompt": S(), "items": arr(obj(["q"], {"q": S(), "options": arr(S())}), 1), "answers": arr(S(), 1)})

SCHEMAS = {
 "role-profile": doc("Role Profile (RPF): industry + department + role + specialisation + seniority (+ employment setting)", obj(
    ["id", "type", "name", "role", "industry", "sector", "department", "specialisation", "responsibilityLevel", "employmentSetting",
     "coreModules", "pilot", "status", "prototype", "publishable"],
    {"id": S(pattern=r"^RPF-\d{6}$"), "type": {"const": "role-profile"}, "name": S(), "role": S(pattern=r"^ROL-\d{4}$"),
     "parentRoles": arr(S(pattern=r"^ROL-\d{4}$")), "industry": S(pattern=r"^IND-\d{4}$"), "industryCode": S(),
     "sector": S(pattern=r"^SEC-\d{2}$"), "sectorCode": S(), "department": S(pattern=r"^DEP-\d{4}$"), "specialisation": S(),
     "responsibilityLevel": S(pattern=r"^SEN-\d{4}$"), "ownershipScale": {"enum": ["solo", "small-team", "company", None]},
     "employmentSetting": S(pattern=r"^EMP-\d{2}$"), "coreModules": arr(S(pattern=r"^CM-\d{2}$"), 1), "reviewTriggers": arr(S()),
     "pilot": S(), "status": {"enum": ["PROFILED"]}, "prototype": {"type": "boolean"}, "publishable": {"const": False}, "notes": arr(S())})),
 "unit-plan": doc("Unit plan for one Role Instance (RIN): profile + CEFR + situation + stakeholder + function", obj(
    ["id", "type", "roleProfile", "situationTemplate", "cefr", "functions", "layers", "reviewPolicy", "maxStatus", "prototype", "publishable"],
    {"id": S(pattern=r"^RIN-\d{6}$"), "type": {"const": "unit-plan"}, "pilot": S(), "roleProfile": S(pattern=r"^RPF-\d{6}$"),
     "situationTemplate": S(pattern=r"^STM-\d{4}$"), "title": S(), "cefr": CEFR, "variantOf": {"type": ["string", "null"]},
     "differFrom": {"type": ["string", "null"]}, "functions": arr(CFN, 1), "excludedFunctions": arr({"type": "object"}), "stakeholders": arr(S()), "constraints": arr(S()),
     "layers": arr(obj(["layer", "key", "objectId", "status"], {"layer": {"enum": ["L0", "L1", "L2", "L3", "L4", "L5", "L6"]}, "key": S(),
        "objectId": {"type": ["string", "null"]}, "status": {"enum": ["PRESENT", "MISSING"]}, "sharedWith": arr(S()),
        "request": {"type": ["string", "null"]}}), 7),
     "reviewPolicy": obj(["aiQa", "editorial", "specialist", "native"], {"aiQa": S(), "editorial": S(), "specialist": S(), "native": S(),
        "specialistReason": S(), "nativeReason": S()}),
     "maxStatus": {"const": "APPROVED"}, "prototype": {"const": True}, "publishable": {"const": False}, "searchTerms": arr(S())})),
 "unit": doc("L6 unit content, generated by ChatGPT, in the D-U14 cycle (Context, Notice, Understand, Guided Practice, Role Practice, Performance Task, Feedback, Review/Retrieval)", obj(
    ["title", "cefr", "context", "notice", "understand", "guidedPractice", "rolePractice", "performanceTask", "feedback", "reviewRetrieval", "answerKey"],
    {"title": S(), "cefr": CEFR,
     "context": obj(["setting", "learnerRole", "stakeholders", "objective", "constraints"], {
        "setting": S(), "learnerRole": S(), "objective": S(), "constraints": arr(S()),
        "stakeholders": arr(obj(["archetype", "name", "relationship"], {"archetype": S(), "name": S(),
                                 "relationship": {"enum": ["external", "senior", "peer", "junior"]}}), 1)}),
     "notice": obj(["conversation"], {"conversation": obj(["turns"], {"turns": arr(obj(["n", "speaker", "learner", "text"], {
        "n": {"type": "integer", "minimum": 1}, "speaker": S(), "learner": {"type": "boolean"}, "text": S(), "functions": arr(CFN)}), 4)})}),
     "understand": obj(["keyExpressions", "vocabulary"], {
        "keyExpressions": arr(obj(["text", "function"], {"text": S(), "function": CFN, "note": {"type": "string"}}), 1),
        "vocabulary": arr(obj(["term", "definition", "example"], {"term": S(), "pos": {"type": "string"}, "definition": S(), "example": S(),
                                                                 "existingCode": {"type": ["string", "null"]}, "tempId": {"type": ["string", "null"]}})),
        "notes": arr(S())}),
     "jobKnowledge": arr(obj(["title", "text"], {"title": S(), "text": S()})),
     "guidedPractice": arr(TASK, 1),
     "rolePractice": obj(["instructions", "cards"], {"instructions": S(), "cards": arr(obj(["role", "goal"], {"role": S(), "goal": S(), "info": {"type": "string"}}), 2)}),
     "performanceTask": obj(["prompt", "modes", "successCriteria"], {"prompt": S(), "modes": arr({"enum": ["speak", "write"]}, 1), "successCriteria": arr(S(), 1)}),
     "feedback": obj(["selfCheck"], {"selfCheck": arr(S(), 1), "rubric": arr(obj(["criterion", "weight"], {"criterion": S(), "weight": {"type": "integer", "minimum": 1}}))}),
     "reviewRetrieval": arr(obj(["prompt", "answer"], {"prompt": S(), "answer": S()}), 1),
     "answerKey": arr(obj(["taskRef", "answer"], {"taskRef": S(), "answer": S()}), 1),
     "coreLinks": arr(S())})),
 "layer-object": doc("L0–L5 layer object content, generated by ChatGPT. Required content fields per layer are checked by ingest.py (LAYER_FIELDS).", {
    "type": "object", "required": ["content"], "properties": {"content": {"type": "object"}}}),
 "stored-object": doc("Stored object envelope (repository-assigned)", obj(
    ["id", "type", "layer", "key", "status", "version", "provenance", "review", "prototype", "publishable", "content"],
    {"id": S(), "type": S(), "layer": {"enum": ["L0", "L1", "L2", "L3", "L4", "L5", "L6"]}, "key": S(), "status": STAT,
     "version": {"type": "integer", "minimum": 1},
     "provenance": obj(["source", "generator", "requestId", "ingestedAt"], {"source": {"enum": ["generated", "human"]}, "generator": S(),
        "model": {"type": ["string", "null"]}, "requestId": S(), "ingestedAt": S(), "tempId": {"type": ["string", "null"]}}),
     "review": obj(["aiQa", "editorial", "specialist", "native"], {"aiQa": RES, "editorial": RES, "specialist": RES, "native": RES}),
     "prototype": {"type": "boolean"}, "publishable": {"type": "boolean"}, "sharedBy": arr(S()), "vocabularyCodes": arr(S()),
     "content": {"type": "object"}})),
 "vocabulary-entry": doc("Engine vocabulary entry (D-U07: V-<SCOPE>-<NUMBER>; existing book codes unchanged)", obj(
    ["code", "term", "definition", "example", "scope", "home", "status"],
    {"code": S(pattern=r"^V-[A-Z]{2,8}-\d{4}$"), "term": S(), "pos": {"type": "string"}, "definition": S(), "example": S(), "scope": S(),
     "cefr": CEFR, "home": S(), "usedBy": arr(S()), "status": STAT, "provenance": {"type": "object"}})),
 "request": doc("Generation request packet (repository → ChatGPT)", obj(
    ["requestId", "contractVersion", "batch", "mode", "layer", "status", "dependsOn", "expectedOutputs", "context", "style", "limits", "estimate"],
    {"requestId": S(pattern=r"^REQ-\d{6}$"), "contractVersion": S(), "batch": S(), "mode": {"enum": ["generate", "revise", "review"]}, "layer": S(),
     "status": {"enum": ["PREPARED", "SENT", "RECEIVED", "INGESTED", "BLOCKED", "STOPPED_BUDGET"]}, "dependsOn": arr(S()),
     "expectedOutputs": arr(obj(["tempId", "type", "key"], {"tempId": S(), "type": S(), "key": S(), "brief": {"type": "object"}}), 1),
     "context": {"type": "object"}, "style": {"type": "object"}, "limits": {"type": "object"}, "outputSchema": {"type": "object"},
     "estimate": obj(["inputTokens", "maxOutputTokens"], {"inputTokens": {"type": "integer"}, "maxOutputTokens": {"type": "integer"}}),
     "instructions": arr(S()), "responseFormat": {"type": "object"}})),
 "response": doc("ChatGPT response packet (ChatGPT → repository)", obj(
    ["requestId", "contractVersion", "outputs", "selfCheck"],
    {"requestId": S(pattern=r"^REQ-\d{6}$"), "contractVersion": S(), "model": {"type": ["string", "null"]},
     "outputs": arr(obj(["tempId", "type", "key", "record"], {"tempId": S(), "type": S(), "key": S(), "record": {"type": "object"}}), 1),
     "selfCheck": arr(obj(["check", "result"], {"check": S(), "result": {"enum": ["met", "not met", "uncertain"]}, "notes": {"type": "string"}})),
     "assumptions": arr(S()), "flags": arr({"type": "object"}), "questions": arr(S())})),
 "review": doc("Review record (D-R09)", obj(
    ["id", "target", "stage", "reviewer", "result", "date"],
    {"id": S(pattern=r"^REV-\d{6}$"), "target": S(), "stage": {"enum": ["AI_QA", "EDITORIAL_REVIEW", "SPECIALIST_REVIEW", "NATIVE_REVIEW"]},
     "reviewer": S(), "result": RES, "reason": {"type": "string"}, "findings": arr({"type": "object"}), "date": S()})),
 "batch-config": doc("Pilot batch configuration (per-batch limits; no global ceiling, D-U10)", obj(
    ["pilot", "contractVersion", "batches", "pricing", "sizeLimits"],
    {"pilot": S(), "contractVersion": S(), "batches": {"type": "object"}, "pricing": {"type": "object"}, "sizeLimits": {"type": "object"},
     "note": {"type": "string"}}, extra=True)),
}

if __name__ == "__main__":
    for name, body in SCHEMAS.items():
        save(store("schemas", f"{name}.schema.json"), body)
    print("schemas:", ", ".join(sorted(SCHEMAS)))
