"""Shared helpers for the role-engine curriculum store (editorial/curriculum/).

The store is architecture-validation work for pilot U-1. It never touches book-data.json, the
website, the PDF or the publication gates, and nothing here compiles or publishes content.

Curriculum text is generated by ChatGPT (author decision D-U10). These tools build the requests,
validate and store the responses, assign IDs and codes, run AI QA, compose and test search.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
EDITORIAL = ROOT / "editorial"
STORE = EDITORIAL / "curriculum"
REFERENCE_INDEX = ROOT / "reference-index.json"

# The live core code pattern used by index.html, build_reference_index.py and build_print.py.
CORE_CODE = re.compile(r"\b(V|PAT|GIC|CF|TL|MIS|TIP|P)-(\d{3,4})\b")
CODE_TYPES = {"V", "PAT", "GIC", "CF", "TL", "MIS", "TIP", "P"}
ENGINE_CODE = re.compile(r"^(V|PAT|MIS)-([A-Z]{2,8})-(\d{4})$")   # D-U07: V-<SCOPE>-<NUMBER>

STATUSES = ["GENERATED", "AI_QA", "EDITORIAL_REVIEW", "SPECIALIST_REVIEW", "NATIVE_REVIEW",
            "APPROVED", "COMPILED", "PUBLISHED", "RETIRED"]
REVIEW_RESULTS = {"PENDING", "PASS", "FAIL", "NOT_REQUIRED", "NOT_PERFORMED"}
CEFR_STANDARD = ["Pre-A1", "A1", "A2", "B1", "B2", "C1", "C2"]

# Bengali and Devanagari blocks: U-1 must contain no Bengali/Hindi content (D-U08 clarification)
L1_SCRIPT = re.compile(r"[ঀ-৿ऀ-ॿ]")


def load(path, default=None):
    path = Path(path)
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def save(path, obj):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")


def store(*parts, base=None):
    return Path(base or STORE).joinpath(*parts)


def core_codes():
    """Every code in the live reference index (the existing book's codes)."""
    ri = load(REFERENCE_INDEX, {"codes": {}})
    return ri["codes"]


def scope_codes(base=None):
    return {c["code"] for c in load(store("registry", "scope-codes.json", base=base), [])}


# ---------------------------------------------------------------- minimal JSON Schema subset validator
# Supports: type, required, properties, additionalProperties(false), enum, const, pattern, items,
# minItems, maxItems, minLength, minimum, maximum, $ref to #/$defs/..., anyOf. (jsonschema is not installed.)
TYPES = {"object": dict, "array": list, "string": str, "integer": int, "number": (int, float), "boolean": bool, "null": type(None)}


def validate(instance, schema, root=None, path="$"):
    root = root or schema
    errs = []
    if "$ref" in schema:
        ref = schema["$ref"]
        assert ref.startswith("#/$defs/"), ref
        return validate(instance, root["$defs"][ref.split("/")[-1]], root, path)
    if "anyOf" in schema:
        if not any(not validate(instance, s, root, path) for s in schema["anyOf"]):
            errs.append(f"{path}: matches none of anyOf")
        return errs
    t = schema.get("type")
    if t:
        ts = t if isinstance(t, list) else [t]
        ok = any(isinstance(instance, TYPES[x]) and not (x in ("integer", "number") and isinstance(instance, bool)) for x in ts)
        if not ok:
            return [f"{path}: expected {t}, got {type(instance).__name__}"]
    if "const" in schema and instance != schema["const"]:
        errs.append(f"{path}: must be {schema['const']!r}")
    if "enum" in schema and instance not in schema["enum"]:
        errs.append(f"{path}: {instance!r} not in {schema['enum']}")
    if isinstance(instance, str):
        if "pattern" in schema and not re.search(schema["pattern"], instance):
            errs.append(f"{path}: {instance!r} does not match {schema['pattern']}")
        if "minLength" in schema and len(instance) < schema["minLength"]:
            errs.append(f"{path}: shorter than {schema['minLength']}")
    if isinstance(instance, (int, float)) and not isinstance(instance, bool):
        if "minimum" in schema and instance < schema["minimum"]:
            errs.append(f"{path}: below {schema['minimum']}")
        if "maximum" in schema and instance > schema["maximum"]:
            errs.append(f"{path}: above {schema['maximum']}")
    if isinstance(instance, dict):
        for k in schema.get("required", []):
            if k not in instance:
                errs.append(f"{path}: missing '{k}'")
        props = schema.get("properties", {})
        for k, v in instance.items():
            if k in props:
                errs += validate(v, props[k], root, f"{path}.{k}")
            elif schema.get("additionalProperties") is False:
                errs.append(f"{path}: unexpected '{k}'")
    if isinstance(instance, list):
        if "minItems" in schema and len(instance) < schema["minItems"]:
            errs.append(f"{path}: fewer than {schema['minItems']} items")
        if "maxItems" in schema and len(instance) > schema["maxItems"]:
            errs.append(f"{path}: more than {schema['maxItems']} items")
        if "items" in schema:
            for i, x in enumerate(instance):
                errs += validate(x, schema["items"], root, f"{path}[{i}]")
    return errs


def schema(name, base=None):
    return load(store("schemas", f"{name}.schema.json", base=base))


def words(text):
    return re.findall(r"[A-Za-z][A-Za-z'’-]*", text or "")


def estimate_tokens(text):
    """Rough token estimate (≈4 characters per token for English JSON). Recorded as an estimate only."""
    return max(1, round(len(text) / 4))


def next_id(prefix, existing, width=6):
    nums = [int(x.split("-")[-1]) for x in existing if re.fullmatch(rf"{prefix}-\d+", x)]
    return f"{prefix}-{(max(nums) + 1 if nums else 1):0{width}d}"
