# Module purposes: rewritten for readers.
# The originals were course-design notes ("Sequence logic: …", "named in the project brief", "the Lead pillar … 0%",
# "working title", "per the project's core pronunciation principle") and appear on the module cards and in the print edition.
PURPOSES = {
    "CE-L01-M01": "Talk about yourself at work — your background, your role and what you do — clearly enough to feel confident in your first real conversations.",
    "CE-L01-M02": "Follow Arif through his first day, from arrival to going home: introductions, a first tour, first tasks and first questions.",
    "CE-L01-M03": "Move from basic greetings to comfortable small talk: choosing formal or informal language, starting a conversation, keeping to safe topics and ending politely.",
    "CE-L01-M04": "Understand instructions completely: listen for the key details, confirm what you heard, organise multi-step tasks, and say clearly when something is unclear.",
    "CE-L01-M05": "Ask for help with confidence: ask someone to repeat or explain, ask a precise clarifying question, and choose the right person and tone.",
    "CE-L01-M06": "Review and extend the workplace vocabulary you have already met — places, people, tasks, tools and task status — so you can use it accurately.",
    "CE-L01-M07": "Learn why tone is part of the message: the PURPOSE → AUDIENCE → MESSAGE → TONE → ACTION framework, polite requests, professional replies and respect for hierarchy.",
    "CE-L02-M01": "Give clear daily updates — in person, under pressure and in writing — and match the amount of detail to the person asking.",
    "CE-L02-M02": "Make and answer requests: add conditions and trade-offs, decline without damaging the relationship, suggest alternatives, pass requests on accurately and write them briefly.",
    "CE-L02-M03": "Use the telephone with confidence: answer and identify yourself, take a message, cope with a bad line, put callers on hold or transfer them, and handle difficult calls.",
    "CE-L02-M04": "Write clear team-chat messages: choose the right register, keep to one idea per message, mark urgency honestly, read the room in group chats and choose chat, call or a conversation.",
    "CE-L02-M05": "Apologise and thank professionally: a three-part apology, owning your own mistakes, specific thanks, and apologising on behalf of your team.",
    "CE-L02-M06": "Follow up well: judge the timing, write a polite reminder, become firmer step by step without being rude, and close the loop when the request is done.",
    "CE-L02-M07": "Serve customers: greet them on any channel, answer questions plainly, admit honestly when you don't know, handle a mild complaint and close the conversation well.",
    "CE-L02-M08": "Workplace etiquette: punctuality and lateness messages, digital etiquette and confidentiality, addressing people at every level, and a full simulated workday.",
    "CE-L03-M01": "Write complete professional emails — requests, information, follow-ups, reminders, confirmations, apologies, complaint replies and escalations — and manage a whole email thread.",
    "CE-L03-M02": "Write short, clear reports with the Facts → Evidence → Analysis → Action → Recommendation framework: routine, incident and performance reports.",
    "CE-L03-M03": "Handle meetings from start to finish: invitations and agendas, opening with an objective, giving opinions and disagreeing politely, action points, closing on time and writing minutes.",
    "CE-L03-M04": "Give a clear presentation: open with a topic and agenda, explain a slide or chart, compare data, move between sections and answer questions calmly.",
    "CE-L03-M05": "Handle complaints from angry customers: listen with empathy, calm the situation, offer an honest solution, escalate in writing when needed, and recover the guest's trust.",
    "CE-L03-M06": "Work with clients: build rapport, find out what they really need, present a solution linked to that need, handle an objection and agree a clear next step in writing.",
    "CE-L03-M07": "Correct the grammar that most often breaks in workplace writing — tenses, modals and conditionals, the passive and reported speech, articles and prepositions, relative clauses and comparatives — using real documents.",
    "CE-L03-M08": "Speak clearly and confidently: word and sentence stress, intonation and rhythm, linking sounds, commonly confused sounds, and speaking without filler words. The goal is clear, natural English, not an imitated accent.",
    "CE-L03-M09": "Communicate across channels: video calls, and choosing between email, chat, phone, video and face to face — adapting one message to each channel without changing the facts.",
    "CE-L04-M01": "Negotiate well: prepare your walk-away point and must-haves, open with an anchor, trade concessions instead of giving them away, stay calm under pressure and confirm the deal in writing.",
    "CE-L04-M02": "Manage difficult conversations: say no firmly, give and receive criticism well, report a serious mistake, deal with a difficult colleague and guide a conflict to a resolution.",
    "CE-L04-M03": "Persuade people: build an argument with evidence, frame it honestly for your audience, find out what a sceptical listener really doubts, and influence colleagues without formal authority.",
    "CE-L04-M04": "Solve problems out loud: break an unclear problem into parts, weigh options with honest trade-offs, and announce a decision and its reasoning — even under time pressure.",
    "CE-L04-M05": "Present to senior audiences: start with your conclusion, handle tough questions, adapt when time is cut or you are interrupted, and use a short story to make a point stick.",
    "CE-L04-M06": "Communicate in a crisis: raise the alarm calmly, deliver bad news honestly, push back on unrealistic deadlines, send clear written updates and see the crisis through to its resolution.",
    "CE-L04-M07": "Work across cultures: recognise differences in communication style, adapt your directness and formality, check understanding with individuals, and avoid stereotypes.",
    "CE-L04-M08": "Manage long-term clients and vendors: keep in touch between deals, renew or renegotiate contracts, hold a vendor to account and reset a client's expectations honestly.",
    "CE-L05-M01": "Give instructions as a leader: delegate clearly, match the detail to the person's experience, hand over real ownership, and follow up without micromanaging.",
    "CE-L05-M02": "Give feedback as a leader: quick everyday feedback, a structured performance conversation, setting goals together and addressing underperformance.",
    "CE-L05-M03": "Coach through questions: tell the difference between telling and coaching, ask open questions, help someone solve their own problem, and know when simply to tell them.",
    "CE-L05-M04": "Lead change: explain the reason behind a decision, announce a change clearly, respond to resistance and keep people on board over time.",
    "CE-L05-M05": "Chair meetings as their owner: open with the outcome you need, decide when the group disagrees, announce a decision not everyone liked, and keep the meeting on time.",
    "CE-L05-M06": "Present as the senior person in the room: open with your own judgment, present a vision, stand behind your call under hard questions, and deliver a full executive presentation.",
    "CE-L05-M07": "Manage your own career in English: CVs and LinkedIn summaries, interviews, networking, asking for feedback and promotion, discussing salary, and resigning gracefully.",
    "CE-L05-M08": "Find your own leadership voice: notice how you naturally communicate, stay yourself under pressure and across channels, and bring every Level 5 skill together in one week.",
}

for module_id, text in PURPOSES.items():
    rule(f"purpose-{module_id}", r"(?s)\A.*\Z", text.replace("\\", "\\\\"),
         "The module description was a course-design note (sequence logic, references to the project brief, curriculum pillars or working titles); rewritten as a short summary for readers.",
         "production", fields=("purpose",), targets=[module_id], expect=1)
